### ISSUE TITLE
Is the project still alive? But why so slow posted commits?

### ISSUE THREAD

**Issue by odil24** [YafaRay/libYafaRay#5]
Really unsuspected and unresponsible.

**Comment by DavidBluecame** [comment]
> Really unsuspected and unresponsible.

Hello,

I find that comment rude, not constructive and untrue.

The project is alive and I've put *a lot* of work on it in the last year. I have explained before that my main objective now is to improve the existing the code and the interface rather than add more features.

You can see all the activity here:
https://github.com/YafaRay/libYafaRay/graphs/contributors

This is the last time I reply to this kind of comment. Next time I see a rude comment like this I will just delete it and close the case.

**Comment by odil24** [comment]
sorry mate

**Comment by DavidBluecame** [comment]
Ok, no problem... just let's keep this a bit more constructive, ok?

FYI: I'm currently investigating to change the entire interface to make YafaRay more maintainable and have a more stable API and ABI, so it can be used more as a library.

That is very little spectacular, requires a lot of investigation and tests to make sure that the changes don't cause other problems and limitations. That and my day job have kept me from sending commits lately, but I'm working hard on trying to understand how the API/ABI, calls, etc, work and looking into some other projects using YafaRay to see how it could impact them.

Best regards.
